-- COPY AND PASTE THESE 3 LINES INTO SUPABASE SQL EDITOR AND CLICK RUN

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.videos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.video_access DISABLE ROW LEVEL SECURITY;
